### PR TITLE
Update qt

### LINKED ISSUE #1863: Travis macOS build is broken
```
installer: Package name is macOS_SDK_headers_for_macOS_10.14
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/usr/local/opt/llvm/bin:$PATH; source scripts/prepare_breakpad_macos.sh; sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /; fi" failed and exited with 1 during .
```

I guess macOS or XCode on Travis got updated and we need to install the system headers differently.

### LINKED ISSUE #2118: Numpad input on UI input fields not working
**Environment information**
* Operating System: Ubuntu 19.10
* Cutter version: 1.10.3 Pre Release
* Obtained from:
  - [X] Downloaded from release

**Describe the bug**

Numpad input does not work on any input field of the UI

**To Reproduce**

1. Go to any input field of the UI, for example "Quick filter" of functions windows, r2 console input. Or open dialogue for putting a comment or renaming a local var. Any input field I tried has the problem.
2. Try to input numbers (or floating point) from numpad and observe they are not being written.

**Expected behavior**

When Num lock is enabled on a keyboard with numpad, input fields of the UI should be able to get input from it.

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**

Update Qt in cutter-deps to latest version - 5.14.2.

**Test plan (required)**
Using the release packages on all 3 OS test that
- Cutter opens
- Make sure ssl library is correctly included and update check works
- sample python plugin works

Platforms tested
- Linux :heavy_check_mark: 
- Windows :heavy_check_mark: 
- macOS 

**Closing issues**
closes #2118

### CODE REVIEW

**Comment by karliss** [comment]
This doesn't work as well. I have one more idea.

**Comment by XVilka** [comment]
Isn't better to target 5.13.2 release instead?

**Comment by karliss** [comment]
@XVilka No objections from me. This was initially done to attempt fixing travis macOS build problem so bugfix release was chosen hoping that it will avoid any new problems. Both assumption turned out to be false. Since there is less urgency now, there is time for dealing with problems caused by bigger version change. Although qt 5.12 is a LTS version.

**Comment by xarkes** [comment]
I'm marking this for next release :)

**Comment by Echelon9** [comment]
Updating Qt dependency to at least 5.12.2 will also resolve https://github.com/radareorg/cutter/issues/2051

**Comment by XVilka** [comment]
Good time to merge this one?

**Comment by karliss** [comment]
Need to get it in working state before anything can be merging. Previous attempt wasn't very successful. Anyone is welcome to try. At point it's probably best updating to latest version available as with recent Qt changes there aren't any LTS versions anymore. 5.14 has some HighDPI improvments.

**Comment by karliss** [comment]
Appimage and windows builds work. I will need help with macOS build.

**Comment by ITAYC0HEN** [comment]
Seems like @a1ext approved it is working on macOS :)

**Comment by karliss** [comment]
Ok, this needs to be merged in proper order starting with cutter-deps-qt.

**Comment by karliss** [comment]
macOS failure was homebrew deciding to take 40 minutes, lets see how it goes for 55d4ee3ce401cc70f550e0d070f2056d012f8548

Documentation failure might be related to python rebuild although it wasn't a problem in earlier builds.

**Pull request merged**
