### PR TITLE
Initial GitHub actions

### PR DESCRIPTION
**Pull request by yossizap**
You can see it live in a [PR on my fork](https://github.com/yossizap/cutter/pull/1) or my [actions](https://github.com/yossizap/cutter/actions).

- Ubuntu fails to build with Shiboken (now disabled) - can't find libclang-7 even though it's installed with apt. Ideas? Also, apt llvm-7/clang-7 isn't available in ubuntu 16.04 so we could manually build+install it. [Failed build here](https://github.com/yossizap/cutter/commit/c08568aad3c2566c2a1a408b5da5a613adf3a8e6/checks?check_suite_id=328183690)
- I'll leave windows support to someone else since the appveyor yml isn't straightforward. 

Docs:
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Can you explain more what is required for the next phases? And are theere any blokcers to merge it before Windows support.
Because it looks like it works in your implementation

**Comment by yossizap** [comment]
It's ready for merging. The next steps are solving Shiboken build issues and windows but those shouldn't matter for automatic PR CI atm. Windows isn't blocking anything since we have appveyor atm and we'll solve shiboken when we want to switch to github action for releases/nightlies.

**Comment by ITAYC0HEN** [comment]
will it be executed in addition to Travis? how will it affect the current experience?

**Comment by yossizap** [comment]
Just additional machines to travis with newer ubuntu/macos. Take a look at PRs in R2.

**Pull request merged**
