### PR TITLE
Fixed a scaling issue of Graph

### PR DESCRIPTION
**Pull request by Vane11ope**
Scaling does not work properly like instructions just disappears as you enlarge and shrink Graph then move.

Now it is just fixed with this.

### CODE REVIEW

**Comment by Adikso** [comment]
Selecting is broken when you zoom in or out. It is selecting wrong line and token.
current_scale is missing from `GraphView::mousePressEvent` and `GraphView::mouseDoubleClickEvent`

Also moving through graph by dragging is slower when you are zoomed out. You have to make a lot of drags. I guess you could scale the offset difference with current_scale in GraphView::mouseMoveEvent

**Comment by Vane11ope** [comment]
Done for all.

**Comment by ITAYC0HEN** [comment]
Tested on Linux. Looks good to me.
@Adikso please approve :)

**Comment by Adikso** [comment]
Double click does not work correctly. current_scale is missing here:
https://github.com/radareorg/cutter/blob/f8cebe0e308f1190b407d9034c43f0db3c986b17/src/widgets/GraphView.cpp#L817-L820

**Comment by Vane11ope** [comment]
here you go

**Comment by ITAYC0HEN** [comment]
@Vane11ope @Adikso what do you think, maybe we should have a single, generic, function to calculate Points and sizes based on scaling? Instead of having all these formulas and maths all over the place. I mean, we know that we'll these problems again in the future where someone would forget about considering the scale.

**Comment by Adikso** [comment]
Looks good to me.

@ITAYC0HEN If somebody forgets about `x / current_scale` or `x * current_scale` he/she will forget about calling scaled(x) too.

**Pull request merged**
