### PR TITLE
MAC Build: new package UI design (thanks to @ITAYC0HEN)

### PR DESCRIPTION
**Pull request by a1ext**
image

### CODE REVIEW

**Comment by a1ext** [comment]
not ready

**Comment by a1ext** [comment]
seems like fixed.

**Comment by ITAYC0HEN** [comment]
Thanks!

**Comment by smarek** [comment]
Do you have source files for the background design ? #1132 needs

**Comment by ITAYC0HEN** [comment]
Yes I have, will solve this PR wit @a14xt next week :)
Thanks!

**Pull request merged**
