### PR TITLE
Reorganize R2GraphWidget UI.

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

* Move custom command input to separate input field. It wasn't obvious that you can enter text in combobox and it also didn't allow easily reacting to enter key.
* Refresh graph on index change and enter key.

**Test plan (required)**

Screenshot from 2020-07-18 18-33-02
Screenshot from 2020-07-18 18-34-48
Screenshot from 2020-07-18 18-34-56

**Closing issues**

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Looks much better and works good!
I would hide the Arrow button (execute) when "User command" isn't selected

**Comment by karliss** [comment]
It is still useful to refresh non-global graphs. Since this is more of a fallback widget for graphs not having proper support, I don't want to make any assumptions here about when it would be useful to refresh.

**Comment by ITAYC0HEN** [comment]
Alright, makes sense, then I'd align it to be right beside the combo box and give up the empty space. "pull-left".

Also, you might want to consider changing the icon to a Refresh icon when it is used with the combo box, and not the text box

**Comment by karliss** [comment]
Slightly changed the behavior. Now when switching graph type input field is kept visible but in disabled state. I hope that it might give some hints to the user about what should be entered in the input field.

**Comment by ITAYC0HEN** [comment]
I don't like change as it's more confusing from the point of UX. It is better not to show any unused element until reaching the "User command" item. With this, if it is worrying that the users won't understand what to write there, we can use a more detailed place holder or a tooltip. `"Enter a graph command such as "..." and "..." ..."`

Also, something I noticed now is that the weird sequence of letters (which isn't clear to the human kind) is taking priority in the names of the commands in the combo box. Instead, I'd go for:

```
Data reference graph (aga)
Global data references graph (agA)
Imports graph (agi)
References graph (agr)
Global references graph (agR)
Cross references graph (agx)
Custom graph (agg)
```

**Comment by karliss** [comment]
r2g

**Pull request merged**
