### PR TITLE
Fix Qt 5.13 deprecations

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by karliss** [comment]
Any thoughts about dealing with isNull checks? Most of them can probably replaced with isEmpty. There might be some that need to differentiate between no string and empty string but it's hard to tell.

**Comment by xarkes** [comment]
If I understood correctly, we should not use any null QString, so I think that using isEmpty everywhere is the proper solution?

**Comment by thestr4ng3r** [comment]
Null and empty strings are definitely different, see https://doc.qt.io/qt-5/qstring.html#isNull (though it says "for historical reasons"). The only thing they deprecated is `QString::null`, which was redundant. In general, "nullish" strings should be constructed like QString() and if we don't want to differenciate between null and empty (most cases), checked with isEmpty().

**Comment by karliss** [comment]
IsNull isn't deprecated yet, but its usage is discouraged. I would suggest slowly remove it. As for the cases that need optional string it might be better to use more explicit approach for indicating that.

**Comment by thestr4ng3r** [comment]
I'm not too sure about that. For instance here, it makes a difference between a string existing and an empty string: https://doc.qt.io/qt-5/qjsonvalue.html#toString. But yeah for our own code, I doubt we will have to use isNull very often.

**Comment by thestr4ng3r** [comment]
In general, I am also more a fan of separating nullability from the actual type like Swift, Rust, Haskell, std::optional, etc. do.

**Pull request merged**
