### PR TITLE
Export graph as SVG, PDF, PNG...

### PR DESCRIPTION
**Pull request by pelijah**
Related: #242.
Requires changes on r2 side: `aggw` is broken at least on Windows.

### CODE REVIEW

**Comment by xarkes** [comment]
Any issue or PR on r2 side?

**Comment by pelijah** [comment]
I will try to fix it now.

**Comment by cyanpencil** [comment]
I think `.ps` stands for PostScript, not for photoshop file.
Sorry if that wasn't too clear in the first place :P

**Comment by Maijin** [comment]
@cyanpencil fixed

**Comment by pelijah** [comment]
I have some problems with it. How can I get offset of current function for `agw filename @ offset`?

**Comment by pelijah** [comment]
@Maijin @cyanpencil

**Comment by pelijah** [comment]
@Maijin

**Comment by Maijin** [comment]
@pelijah Let me know what you need from me, merge?

**Comment by pelijah** [comment]
Yes, I have no more commits for this PR.

**Pull request merged**
