### PR TITLE
Fix references to pkg-config in lib_radare2.pri for Unix

### PR DESCRIPTION
**Pull request by mauronz**
In Unix systems (not macOSX) radare2 is installed under /usr and pkg-config files are put under /usr/lib/pkgconfig. For macOSX instead the /usr/local should be used, although I cannot test it because I do not have a mac system.

[https://github.com/radare/radare2/blob/master/sys/build.sh](url)
From line 15

Also, I think the logic should be correct now: if r_core.pc is found, use pkg-config, otherwise set LIB and INCLUDEPATH manually and set USE_PKGCONFIG to 0.

### CODE REVIEW

**Comment by xarkes** [comment]
Can't tell if that's because of your modifications but qmake is failing:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks -o Cutter.app/Contents/MacOS/Cutter Main.o Cutter.o DisassemblerGraphView.o RichTextPainter.o OptionsDialog.o AboutDialog.o CommentsDialog.o EditInstructionDialog.o FlagDialog.o RenameDialog.o XrefsDialog.o MainWindow.o Helpers.o HexAsciiHighlighter.o HexHighlighter.o Highlighter.o MdHighlighter.o AsmOptionsWidget.o NewFileDialog.o AnalTask.o CommentsWidget.o ConsoleWidget.o Dashboard.o EntrypointWidget.o ExportsWidget.o FlagsWidget.o FunctionsWidget.o ImportsWidget.o Omnibar.o PieView.o RelocsWidget.o SdbDock.o SectionsWidget.o Sidebar.o StringsWidget.o SymbolsWidget.o DisassemblyContextMenu.o DisassemblyWidget.o SidebarWidget.o HexdumpWidget.o Configuration.o Colors.o SaveProjectDialog.o TempConfig.o SvgIconEngine.o SyntaxHighlighter.o PseudocodeWidget.o VisualNavbar.o GraphView.o PreferencesDialog.o GeneralOptionsWidget.o GraphOptionsWidget.o PreferenceCategory.o QuickFilterView.o ClassesWidget.o ResourcesWidget.o VTablesWidget.o TypesWidget.o HeadersWidget.o SearchWidget.o CutterApplication.o JupyterConnection.o JupyterWidget.o PythonAPI.o NestedIPyKernel.o R2PluginsDialog.o CutterDockWidget.o CutterSeekableWidget.o GraphWidget.o JsonTreeItem.o JsonModel.o VersionInfoDialog.o ZignaturesWidget.o AsyncTask.o AsyncTaskDialog.o StackWidget.o RegistersWidget.o BacktraceWidget.o qrc_resources.o qrc_style.o moc_Cutter.o moc_DisassemblerGraphView.o moc_CachedFontMetrics.o moc_AboutDialog.o moc_AsmOptionsWidget.o moc_CommentsDialog.o moc_EditInstructionDialog.o moc_FlagDialog.o moc_RenameDialog.o moc_XrefsDialog.o moc_HexAsciiHighlighter.o moc_HexHighlighter.o moc_MainWindow.o moc_Highlighter.o moc_MdHighlighter.o moc_OptionsDialog.o moc_NewFileDialog.o moc_AnalTask.o moc_CommentsWidget.o moc_ConsoleWidget.o moc_Dashboard.o moc_EntrypointWidget.o moc_ExportsWidget.o moc_FlagsWidget.o moc_FunctionsWidget.o moc_ImportsWidget.o moc_Omnibar.o moc_PieView.o moc_RelocsWidget.o moc_SdbDock.o moc_SectionsWidget.o moc_Sidebar.o moc_StringsWidget.o moc_SymbolsWidget.o moc_DisassemblyContextMenu.o moc_DisassemblyWidget.o moc_SidebarWidget.o moc_HexdumpWidget.o moc_Configuration.o moc_SaveProjectDialog.o moc_SyntaxHighlighter.o moc_PseudocodeWidget.o moc_VisualNavbar.o moc_GraphView.o moc_PreferencesDialog.o moc_GeneralOptionsWidget.o moc_GraphOptionsWidget.o moc_QuickFilterView.o moc_ClassesWidget.o moc_ResourcesWidget.o moc_CutterApplication.o moc_VTablesWidget.o moc_TypesWidget.o moc_HeadersWidget.o moc_SearchWidget.o moc_JupyterConnection.o moc_JupyterWidget.o moc_R2PluginsDialog.o moc_CutterDockWidget.o moc_CutterSeekableWidget.o moc_GraphWidget.o moc_VersionInfoDialog.o moc_ZignaturesWidget.o moc_AsyncTask.o moc_AsyncTaskDialog.o moc_StackWidget.o moc_RegistersWidget.o moc_BacktraceWidget.o   -F/usr/local/Cellar/qt/5.11.0/lib -F/Users/travis/build/radareorg/cutter/python/framework -framework Python -L/usr/local/lib -lr_core -lssl -lcrypto -lz -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_parse -lr_flag -lr_cons -lr_reg -lr_search -lr_syscall -lr_fs -lr_io -lr_socket -lr_magic -lr_crypto -lr_hash -lr_util -ldl -framework QtSvg -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtWebEngineWidgets -framework QtWebEngineCore -framework QtQuick -framework QtQml -framework QtNetwork -framework QtWebChannel -framework QtPositioning -framework QtPrintSupport -framework OpenGL -framework AGL 
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mauronz** [comment]
The problem should be that one of the files in the pkg-config contains a reference to the ssl library. I have no idea where that comes from, since in Linux it doesn't appear. Anyway a temporary fix would be to not consider pkg-config entirely. That is basically what the master version is doing on OSX, but at least we can extend the same behavior to Linux.

**Comment by xarkes** [comment]
Is it good to merge?

**Comment by mauronz** [comment]
Yes. For mac it works as before, for Linux it uses correctly the pkg-config.

**Comment by xarkes** [comment]
Ok, thank you.

**Pull request merged**
