### PR TITLE
Graph highlighting

### PR DESCRIPTION
**Pull request by Adikso**

### CODE REVIEW

**Comment by xarkes** [comment]
Can you paste a screenshot of the result?

**Comment by Adikso** [comment]
screenshot_20180816_135500
screenshot_20180816_135226

**Comment by xarkes** [comment]
Cool that's nice, thank you.

**Comment by ITAYC0HEN** [comment]
This solves another line in the highlighting tracker :)
https://github.com/radareorg/cutter/issues/97
Well done!

**Pull request merged**
