### PR TITLE
More Delay in macOS Background Script

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by karliss** [comment]
I have always thought that creating an installer by scripting a file browser to move icons is weird and apple should have provided better tools. 

Not for this PR but maybe it's worth investigating alternative approaches for dmg background configuration. For example there is https://pypi.org/project/dmgbuild/ .

**Comment by thestr4ng3r** [comment]
Agreed, cc @a1ext

**Comment by a1ext** [comment]
@thestr4ng3r does it work now?

**Comment by thestr4ng3r** [comment]
No, unfortunately not. You can see in the logs it still fails there: https://travis-ci.org/radareorg/cutter/jobs/580730929#L6394

**Pull request merged**
