### PR TITLE
[WIP] added widget to view register values

### PR DESCRIPTION
**Pull request by fcasal**

### CODE REVIEW

**Comment by xarkes** [comment]
Why did you call it DebugWidget while it's only registers?

**Comment by Maijin** [comment]
Also If we call it DebugWidget, it will probably require name refactoring when doing the emulation part which will the same elements

**Comment by xarkes** [comment]
You can also update the radare2 submodule in your PR (I see that one commit depends on new r2 commits).

**Comment by xarkes** [comment]
Missing include for OsX:
```
../src/widgets/StackWidget.cpp:20:32: error: member access into incomplete type 'QHeaderView'
    viewStack->verticalHeader()->hide();
```

**Pull request merged**
