### PR TITLE
Update radare2 submodule

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by xarkes** [comment]
To merge or not to merge, that is the question... Can't we wait for a buildable version of r2?

**Comment by XVilka** [comment]
Wait for a few days, more important fixes will come.

**Comment by ITAYC0HEN** [comment]
We can update again, no problems ;)

**Comment by thestr4ng3r** [comment]
Let's update right now, there's also a fix for meson in there that I need.

**Pull request merged**
