### PR TITLE
Automating translations updates

### PR DESCRIPTION
**Pull request by xarkes**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This PR aims at automating the upload of new strings to the cutter-translations repository.
It generates a new `.ts` file and pushes it to cutter-translations repository.

Then, Crowdin will regularly fetch cutter-translations, parse the file to update new strings, and push the translations to the same repository.
For that, we'll have to modify a bit how the `.qm` files are generated from the `.ts` files during release process, as Crowdin pushes the files in separate folders, which is different from what we have today in https://github.com/radareorg/cutter-translations.

What hasn't been tested:
- Does the script fail during commit/push if no modification was made to `Translation.ts`?

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
What is the indication if it worked?

**Comment by xarkes** [comment]
There is none, and it did not :p
More seriously, I need to fix the check on the branch name although it is supposed to work only on the master branch on long term.
After I've generated the proper token on Travis, it should push a new commit on the cutter-translations repository (that's the indication).

**Comment by xarkes** [comment]
Ok I think this PR is ready for review.

**Review by ITAYC0HEN — APPROVED** [review]

**Comment by xarkes** [comment]
I fixed Crowdin configuration, fixed link to files in `Cutter.pro` due to changes in https://github.com/radareorg/cutter-translations, I think it is good to merge now.

**Review by ITAYC0HEN — APPROVED** [review]

**Review by ITAYC0HEN — APPROVED** [review]

**Pull request merged**
