### PR TITLE
Jupyter implementation

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by pelijah** [comment]
For meson you can use this patch
```diff
diff --git a/src/meson.build b/src/meson.build
index 2484710..0cbc467 100644
--- a/src/meson.build
+++ b/src/meson.build
@@ -47,5 +47,5 @@ cutter_exe = executable(
   gui_app: not console,
   sources: sources,
   include_directories: platform_inc,
-  dependencies: [libr2_dep, qt5dep],
+  dependencies: [libr2_dep, qt5dep, dependency('python3')],
 )
diff --git a/src/utils/JupyterConnection.h b/src/utils/JupyterConnection.h
index a408c97..70cc49a 100644
--- a/src/utils/JupyterConnection.h
+++ b/src/utils/JupyterConnection.h
@@ -2,6 +2,7 @@
 #define JUPYTERCONNECTION_H

 #include <QProcess>
+#include <QMap>

 class NestedIPyKernel;
```

**Comment by pelijah** [comment]
default

**Comment by xarkes** [comment]
Nice thanks

**Comment by pelijah** [comment]
Well we need to move all environment settings from prepare_r2.bat/build.bat to appveyor script. I will do it later.

**Comment by xarkes** [comment]
Ok thanks.

**Comment by xarkes** [comment]
Actually what do you mean move? It might be useful for Windows users if there is a default settings in the .bat scripts, right?

**Comment by pelijah** [comment]
IMO it is useless for most users because most users have unique environment (VS version, Qt version, Qt path, python path). So they still have to set environmennt variables manually.

**Comment by pelijah** [comment]
Can you add some debug messages `message($$pythonpath)`?

**Comment by pelijah** [comment]
You need to use `message()` instead of `$$message()`.

**Comment by pelijah** [comment]
Try with this:
```qmake
pythonpath = $$quote($$system("where python"))
pythonpath = $$replace(pythonpath, ".exe ", ".exe;")
pythonpath = $$section(pythonpath, ";", 0, 0)
pythonpath = $$clean_path($$dirname(pythonpath))
```

**Comment by pelijah** [comment]
Hah first bitness problem:

> (Link target) -> 
>          python36.lib(python36.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86' [C:\projects\cutter\build32\cutter.vcxproj]

**Comment by xarkes** [comment]
Well yes, the 32bits build is using Python x64.
```
Info: creating stash file C:\projects\cutter\build32\.qmake.stash
Project MESSAGE: C:/Python36-x64
```

**Pull request merged**
