### PR TITLE
Disable the debug window menu outside Debug/Emulation mode (resolves #859)

### LINKED ISSUE #859: Debug-related widgets shouldn't be available outside Debug\Emulation mode
**Describe the bug**
Currently, a user can open the debug-related widgets even if they aren't in debug mode. This will obviously show wrong information and might cause confusions.

**To Reproduce**

Click on the "Windows" menu item, choose "Debug..." and select a debug-related widget

**Expected behavior**
When not in debug\emulation mode, I expect the "Debug" item to be grayed out.

image

### PR DESCRIPTION
**Pull request by xift**
This commit grayes out the debug windows menu when not debugging.
I stumbled upon this project while browsing the hacktoberfest issues and really like it. Hope I can contribute in the future.

Best,
Michael

### CODE REVIEW

**Comment by xarkes** [comment]
Hi, the PR looks good to me :)
Build is failing on macOS but I think it is unrelated.

**Comment by ITAYC0HEN** [comment]
we fixed an issue in Travis, can you please rebase your PR? :)

**Comment by ITAYC0HEN** [comment]
we fixed an issue in Travis, can you please rebase your PR? :)

**Comment by xarkes** [comment]
No it's fine, I trust the changes :)

**Comment by xift** [comment]
Thanks :-)

**Pull request merged**
