### PR TITLE
Update r2 submodule.

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

R2 4.5 will be released soon. Update r2 to try catch any problems before that and reduce delay until we can release compatible Cutter release.

**Test plan (required)**

CI  is green.
Basic sanity checks that everything isn't completely broken:
* Open executable
* Check that disassembly, graph view and hexwidget look reasonable
* Start debuging, set a breakpoint, make sure it is hit
* Do some single stepping make sure registers are refreshed

**Closing issues**

### CODE REVIEW

**Comment by xarkes** [comment]
On AppVeyor:
```
src\subprojects\radare2\test\unit\meson.build:53:4: ERROR: Unknown variable "rpath".
```

**Comment by karliss** [comment]
> ```
> src\subprojects\radare2\test\unit\meson.build:53:4: ERROR: Unknown variable "rpath".
> ```
Yes, I will disable r2 unit tests for now. There is no need for us to build or run them.

**Comment by xarkes** [comment]
Did you try Cutter with this version to make sure nothing is broken?
I will try to try that during the weekend.

**Comment by karliss** [comment]
Basic stuff works. Restarting debug session doesn't work properly but someone was complaining about it in 1.10.3 as well. Would be good to fix though.

**Pull request merged**
