### PR TITLE
Fix sorting resources by index, vaddr and size

### LINKED ISSUE #2272: Sort by Resource "Size" is incorrect
**Environment information**
* Operating System: Debian
* Cutter version: v1.10.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: PE32

When sorting by "size" in resource page, it sorts by string-order and not numerical order.

**To Reproduce**

1. Go to 'resources' tab
2. Click on 'size' column
3. See error

**Expected behavior**

Sort by numerical order and not string.

**Screenshots**

cutter-sort-by-resource-size

### PR DESCRIPTION
**Pull request by polaris**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This is supposed to be a fix for issue #2272 . The problem was that sorting was done using a "byte-count" formatted string which should be only used for displaying (`Qt::DisplayRole`). This fix uses `Qt::EditRole` as the sorting role. `ResourcesModel::data()` returns the correct value depending on the parameter `role`:

* a byte-count formatted string in case of `Qt::DisplayRole`
* the numerical byte count in case of `Qt::EditRole`

**Test plan (required)**

1. Launch Cutter and load a PE32 file
2. Go to 'Resources' tab
3. Sort by "Size"

Sorting is done by numerical order and not string.

Closes #2272

### CODE REVIEW

**Comment by karliss** [comment]
Doesn't vaddr and index have the same problem?

**Comment by polaris** [comment]
Well, you are right, they do. I'm going to re-work the PR.

**Comment by Surendrajat** [comment]
Thanks for the PR! A few suggestions:
- If you think a PR will close an issue, please add `Closes #ISSUE_NUMBER` at the end of the PR description.
-  Until it's ready, you can convert it to draft too (same as WIP)

**Comment by karliss** [comment]
Thank you for the PR. We haven't forgotten about it. We are currently in the process of preparing new release so it might take a few days until this can be handled.

**Comment by ITAYC0HEN** [comment]
Good work @polaris! :) Thank you!

**Pull request merged**
