### PR TITLE
Fixed file name display in new file dialog

### PR DESCRIPTION
**Pull request by xarkes**
Before:
Cf the linked issue below

Now:
image

This is not the intended solution, but I think it's fine as well.

Fixes https://github.com/radareorg/cutter/issues/1642

### CODE REVIEW

**Comment by karliss** [comment]
This might be the opposite extreme. When working with multiple variations of the same binary it would be as bad if not worse than  current approach with long names.

From the few programs with similar recent file/project list all of them used following approach - show project name (file name in our case) using contrasting color, show directory or full path on second line with less contrasting color.

Screenshot from 2019-07-19 22-07-22
Screenshot from 2019-07-19 22-08-10
Screenshot from 2019-07-19 22-08-26

**Comment by karliss** [comment]
[VS2019](https://devblogs.microsoft.com/cppblog/wp-content/uploads/sites/9/2019/01/start-window1.jpg) , and [Xcode](http://worldwebscapes.com/wp-content/uploads/2019/01/Step-One-1024x556.png) also do the same.

**Comment by ITAYC0HEN** [comment]
I agree with @karliss on this. I prefer seeing the full path than seeing only the filename. Best option, as suggested, would be to show the folder name (short version  ~) an file name with different colors or emphasis. This shouldn't take a lot of space

**Comment by xarkes** [comment]
Sure I just made a quick fix but I can definitely improve it.

**Comment by xarkes** [comment]
New display:
image

**Comment by xarkes** [comment]
It'd be great if someone could test it on Windows though.

**Comment by JorgeTebruski** [comment]
Windows:

Anotação 2019-07-20 130628

**Comment by xarkes** [comment]
I fixed the variable name for Windows, but I think it's not going to be enough.

**Comment by xarkes** [comment]
But in fact my solution is shit, I should use that: https://doc.qt.io/qt-5/qdir.html#homePath

**Comment by JorgeTebruski** [comment]
Apparently the problem was solved.

**Comment by ITAYC0HEN** [comment]
@xarkes are you satisfied with your solution yet?

**Comment by xarkes** [comment]
Oh yes sorry, I was busy, yep looks good to me.

**Pull request merged**
