### PR TITLE
Native and remote debug support

### PR DESCRIPTION
**Pull request by yossizap**
**Detailed description**

Prepare the debug branch for release.

**Test plan (required)**

All of the current features were already tested in their original PRs.

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Whoever merges, this should not be stashed

**Comment by karliss** [comment]
Did you meant "should not be squashed"?

**Comment by yossizap** [comment]
I think that we'll be ready to merge once #1919 is merged. Might do another PR for small fixes soon but it could also be merged into master.

**Comment by ITAYC0HEN** [comment]
Finally! I'm really excited! 
Good job @yossizap @fcasal! 

I'm merging 
:)
@radareorg/cutter please be aware and keep an eye out for bugs in the feature

**Pull request merged**
