### PR TITLE
New disassembly widget

### PR DESCRIPTION
**Pull request by xarkes**
This PR is a work-in-progress by the team. Any of you can push changes to this repo. The goal is to make it stable and trust-worthy as the first part, and then merge. Similarly to what @karliss did with Hex widget. Later, improvements and new features would be added.

### Remaining work to do
- [x] Fix arrow positioning
- [x] Fix arrows head
- [x] Improve the algorithm to have something thinner and more good looking
- [x] Fix remaining TODO in the code

### CODE REVIEW

**Comment by optizone** [comment]
what do you think about drawing arrows inside of text edit? like this (obviously not in this position, I just didn't finish the code)
image

Don't know about you, but the fact that arrows are in different widget triggers me. Especially because of this frame around text edit that separates disasm widget and jump arrows
image

**Comment by ITAYC0HEN** [comment]
You can hide border-left if it doesn't feel right to you.
I'm okay with using a different widget. Also, we wanted to allow the user
to copy the disassembly without ascii arrows or anything similar.

**Comment by optizone** [comment]
arrows are just drawn on the text editor, user cannot copy them

**Comment by ITAYC0HEN** [comment]
As long as it looks good, we'll written and easy to maintain, I'm in for every idea

**Comment by xarkes** [comment]
I'm okay with your suggestion @optizone, but I think we want that the user must be able to resize this "arrow area".

**Comment by optizone** [comment]
> I'm okay with your suggestion @optizone, but I think we want that the user must be able to resize this "arrow area".

it is possible too. Just little harder to implement

**Comment by xarkes** [comment]
Well it starts to look good, see the screenshots below:
image
image

**Comment by xarkes** [comment]
@optizone Can you squash your commits so this PR has only 2 commits (one from me, one from you), so I can merge after release?

**Pull request merged**
