### PR TITLE
Indicator that tells a command is being executed is implemented.

### PR DESCRIPTION
**Pull request by Vane11ope**
gifrecord_2018-10-10_030806

### CODE REVIEW

**Comment by Vane11ope** [comment]
https://github.com/radareorg/cutter/issues/764

**Comment by ITAYC0HEN** [comment]
As we spoke, please show the indicator after ~1 second so it won't be shown when executing immediate-commands

**Comment by Vane11ope** [comment]
done

**Comment by xarkes** [comment]
Thanks!

**Pull request merged**
