### PR TITLE
Expose asm.reloff.flags in Preferences

### PR DESCRIPTION
**Pull request by Surendrajat**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**
This PR adds `asm.reloff.flags` checkbox under *Preferences* -> *Disassembly*.

asm-reloff-flags

**Test plan (required)**
Go to *Preferences* -> *Disassembly* -> check *Show offsets relative to a flag (asm.reloff.flags)*

**Closing issues**

### CODE REVIEW

**Comment by karliss** [comment]
I am slightly worried about clutter the first page with too many rarely used settings. @ITAYC0HEN what do you think?

**Comment by ITAYC0HEN** [comment]
For this specific case it can use different ui components, for example 

```
Show offset as relative to:    [x] Functions [ ] Flags
Show offset as relative to:    [ ] Functions [x] Flags
Show offset as relative to:    [x] Functions [x] Flags
Show offset as relative to:    [ ] Functions [ ] Flags
```
Or a combo box maybe (like I did with comments). 



In general, I was thinking about it as well, and I see couple of ways we can go. Of course, some of them can be combined. 

1. First of all, the most complicated one, is refactoring of the whole thing into a modern setting widget (e.g vscode's). I think that Binja has something similar as well. This includes full descriptions, automatically creating the view etc. And of course with a quick filtering and a way to work together with a command pallette in the future.

2. Turn the dialog into a dockable widget. This will allow more space and the items will look less crowded

3. Use group boxes to gather related configurations together in a logical way. This will make it visually easier to navigate in the view.

4. Use more tabs, and group configurations together in a logical way

5. Use sub-items in the side bar to organize configurations in a logical way

6. Use collapsible part at the bottom of the view to hide less-common config

**Comment by Surendrajat** [comment]
@ITAYC0HEN For this change I like the first idea you suggested. It'll save up space and will be consistent with the current logic of `graph.offset` which won't really fit in the comboBox.
About the entire preference view change, yes, I like that idea too but I am not quite ready to pick. If base is set, I can add things to it :)

**Comment by Surendrajat** [comment]
This is how it looks like now:
update-asm-reloff-flags

**Comment by ITAYC0HEN** [comment]
I think that "Show offsets relative to" can also be grayed out when asm.offset is disabled :)

**Comment by Surendrajat** [comment]
@ITAYC0HEN Cool. It's done now. I've rebased and the build is broken but it should work.

**Pull request merged**
