### PR TITLE
Hexedit

### LINKED ISSUE #1057: Support endianess in Hexdump Widget
Support endianess in Hexdump Widget

### LINKED ISSUE #1060: Support hex.pairs eval variable in Hexdump Widget
Support hex.pairs eval variable in Hexdump Widget

### LINKED ISSUE #1064: Support change format in Hexdump Widget
Support change format in Hexdump Widget -  words, dwords, qwords, ..(`pxh`, `pxw`, `pxq`) on right click (see `px?`)

### LINKED ISSUE #1068: Copy start address in Hexdump context menu
Copy start address (show address) in Hexdump context menu

### LINKED ISSUE #1472: Add decimal, 1-byte, half words, words and dwords format in the hexdump
**Is your feature request related to a problem? Please describe.**

To show the hexdump in decimal, 1-byte, half words, words and dwords format

**Describe the solution you'd like**

Add right click format -> decimal, 1-byte, half words, words and dwords format (there is already hex and octal)

### LINKED ISSUE #1473: Add right click Endianness -> Little Endian, Big Endian in hexdump
**Is your feature request related to a problem? Please describe.**

To be able to visualize hexdump data depending onthe endianess

**Describe the solution you'd like**

Add right click Endianness -> Little Endian, Big Endian in hexdump

### LINKED ISSUE #1487: Improve hexdump widget performance
Test 1
* open only disassembly output and try dragging mouse over the global scrollbar at top
* open hexdump widget and repeat step above, observe that  scrolling disassembly was smoother

Doesn't seem right as display hexdump should be much simpler than disassembling and coloring asm code.

Test 2
* Open hexdump widget and scroll down (preferably using a mouse that has freely spinning mouse wheel). Observe that once every x lines scrolling freezes for at least 0.5s, I assume that this is where it loads next chunk. Freezing is shorter when scrolling up.

### LINKED ISSUE #1494: HexWidget refactoring
Issue for tracking information about the hexWidget in [hexedit](/radareorg/cutter/tree/hexedit)/ [karliss/hexedit](/karliss/cutter/commits/hexedit2) branch. 

Issues fixed by switching to the new hexWidget:
* #1473 #1057 endian selection
* #1472  #1064 word size and format
* #1487 performance
* #1060  currently implements the drawing logic, but doesn't read value from hex.pairs.
* #1068 - copy address

Missing functionality compared to current hex widget:
- [x] handleRaiseMemoryWidget
- [x] bidirectional synchronization with other widgets
- [x] sync/unsync option
- [x] basic copy (preferably should respect cursor side)
- [x] Ctrl-shift-c copy address
- [x] right half of current hexdumpWidget
- [x] range selection dialog
- [x] font size refresh
- [x] test in highDPI configuration 

❌ zoom functionality - shouldn't be necessary if font size setting and highDPI scaling is respected

Other issues:
- [x] Internal width doesn't get properly resized when changing size/format. Gets resized when  dockWidget is resized.
- [x] font update bug
- [x] keyboard actions not working
- [x] position sometimes gets set to end of address range

Non critical issues:
- ~~Gap between address and item columns seems to  be bigger than item and ascii~~ probably was caused by wrong font
- Decide what to do with selection that doesn't match word size (leave as is, display in a special way, force word size alignment)
- When resizing docks cursor sometimes stuck in horizontal arrow mode. Not sure if this is specific to the hexWidget .

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**

This PR replaced the main part of hexdump widget with one that is written from scratch. Thanks @pelijah for writing the initial implementation.

**Test plan (required)**
* basic functionality
  * Shows bytes ✔
  * Scroll to top ✔
  * selection works
    * selecting bytes ✔ 
    * selecting text ✔
    * synchronization between selecting text and bytes ✔
    * select forwards and backwards ✔
    * near the end and start of line ✔
    * shift click ✔
  * keyboard navigation 
    * arrows ✔
    * pageup/down ✔
    * start/end of line ✔
    * selection for all of above ✔
    * near the ends ✔
  * copy bytes ✔ *3
  * copy text ✔
  * copy address (menu and shortcut) ✔
  * changing display mode (each setting at least once + some combinations) 
    * item size ✔
    * format ✔
    * columns ✔ *0
    * hexpairs ✔
    * endian ✔
* right panel
  * selection gets updated when selecting ✔
  * correct range (check using one of byte printers) ✔
  * changing display mode works ✔
* seek synchronization
  * seek in the colored bar at top ✔
  * function list ✔
  * disassm ✔
  * seek in hexdump changes global seek ✔ *1
  * sync/unsync in context menu disables seek synchronization both ways ✔
* setting changes
  * font change ✔
  * color change ✔
* high dpi mode *2

*0 It is possible to force unaligned offset by increasing column count, gets aligned when scrolling - should probably create an issue for adding switch to enable/disable offset alignment. Would be useful for inspecting unaligned multibyte integers, floats.
*1 disasembly widget doesn't like seeking to the middle of instruction - out of scope for this issue
*2 side panel restoration button gets pixelated - should be fixed together with other icons
*3 currently always gets copied as bytes - should create two follow up issues. One for changing default copy behavior to copy exactly as displayed. Second for adding "copy as" menu which allows copying in various formats supported by r2 `p` commands.

hexwdiget

**Closing issues**

closes #1473, closes #1057, closes #1472, closes #1064, closes #1487, closes #1068 (was already implemented in old hex widget), closes #1494 

~~Doesn't close~~ Keeps #1060 open - implements the drawing mode but doesn't synchronize the setting.

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
woah! very good work, love it!
Didn't go over the code yet, but I have some insights and notes from using it.
These are some ideas and requests, please feel free to decide otherwise:

Bugs:
 - Columns confusion:
    1. Start from Item Size: 1 and Columns: 16
image

    2. Enable hex.pairs
    3. Change Item Size to 4
    4. Change Item Size to 1 (Item Size: 1 Columns: 16)
image

As you can see, only 8 columns are shown (16/2)




Suggestions and requests:

1. use `00 01 02 03` instead of `0 1 2 3` in the hexdump header. This would look better in terms of column alignment and will also look better when using more that 16 columns. Now it is `D E F 10 11 12` and it would look better if it would have been `0D  0E  0F  10  11  12`

2.  Addresses are not selectable. Should they? I can see how someone would try to select them. I did

3. Addresses are 64bits even on 32bits or 16bits binaries. Would be better to use the opened binary bits (`asm.bits`) and fall back to 32 or 64.

4. Putting the cursor in Ascii column would select with dashed pen the lower half of the byte instead the whole byte.  In the Following image, I would expect `fe` to be selected and not only `f`
image

5. Right click somewhere in the hexdump should change the cursor location (Even if temporarily). So say my curser is in place A and I right clicking on byte Y and selecting "Copy Address", I expect the address to be copied would be the address of Y.

6. Instead of "hex.pairs" write "Show bytes paired"

7. When selecting bytes in Hex or ASCII the respective bytes\letters in the other columns is selected as well. Would be very nice if the selected bytes in the other columns would be the beautiful QPen with the dashed gray border with no bg color. quite similar to what Binja have in the right column here:
image

8. I prefer the cursor indicator to highlight byte instead of putting a pipe after the byte. Similar to insert mode. Ideally, it will highlight lower\higher bits of the byte
image
and
image

**Comment by karliss** [comment]
@ITAYC0HEN 

0. Good catch. This is a good excuse for switching to fixed by width from fixed columns. C
1. Sounds good
2. Since everything is painted manually it will be a pain to implement any extra selection. At least there is copy address functionality.
3. #1522
5. Easiest thing to do would be for right clicking outside selection to remove the selection and move the cursor.
6. Already suggested by thestr4ng3r and fixed.
7. Would be nice to have. Created seperate issue. #1523
8. I suggest leaving nibble selection to write mode implementation. Insert mode cursor requires slightly different selection behaviour. Need to carefully plan how it will interact with multibyte and non hexadecimal views. #715

**Comment by pelijah** [comment]
1) r2 doesn't fill header offsets with zeros
3) r2 uses 64-bit addresses even for 32-bit binaries. Maybe it is a bug, I don't know.

**Comment by karliss** [comment]
@ITAYC0HEN 0, 4, 5 is fixed. Do you think anything of the remaining issues are critical for first version?

**Comment by ITAYC0HEN** [comment]
I will check soon and will let you know :)

**Comment by radare** [comment]
🥂

**Pull request merged**
