### PR TITLE
Fix issue #935

### LINKED ISSUE #935: Auto-refresh contents after importing PDB
After importing a PDB file, the function names are not updated until you click "refresh contents" button.

### PR DESCRIPTION
**Pull request by ICEBERG98**
The following changes -
    1. Adds More documentation to header files include in MainWindow.cpp
    2. Adds a refreshAll() call at importPDB function
        -- in order to resolve issue #935 here:-
        -- [/issues/935]

**Closing issues**

closes #935 

Thanks!
This is my first time contributing to open source, so, reviews and guidance are highly acknowledged.
Thanks again 👍

### CODE REVIEW

**Comment by ICEBERG98** [comment]
Ok, Thanks. Reopening this PR

**Comment by ICEBERG98** [comment]
> Update your Pull-request using push -f or new commits, don't close nor reopen new PR please

Um, I'm sorry i didn't understand you. Should I not make a PR at all? or should i not reopen them?
Are you saying that i should update my PR's with push -f?
Sorry for my negligence.

**Comment by ITAYC0HEN** [comment]
Hey! :)
Your pull request looks good to me. Thank you! 
Is there anything you want to improve or add to it? If so, please let us know before we merge. 

If you do, you can always update a currently opened Pull Request with new changes. You can do this by pushing your changes to your branch  - in this case "FixIssue_#935". 

A generic PR process would look like this:
```
git clone https://github.com/radareorg/cutter
git remote add iceberg https://github.com/ICEBERG98/cutter
git checkout -b myFeatureBranch

<do cahnges here>

git commit -a -m "description for your commit"

git push iceberg 
< here you should be asked for credentials/ssh key >
```

After pushing changes to your branch, and your branch to github, you will see that you can make a PR from Cutter's page on Github.

You probably done something similar to this when you did this PR.

Now, if you want to update your PR, before it get merged, simple do:

```
git checkout myFeatureBranch
<do changes here>
git commit -a -m "description for your commit"
git push iceberg
```

And this would automatically update your PR with the new changes.

**Comment by ICEBERG98** [comment]
Yeah, Absolutely good by my side. 👍

**Pull request merged**
