### PR TITLE
Analysis maximum basic block fix

### PR DESCRIPTION
**Pull request by xarkes**
The option was changed to anal.bb.maxsize, but the format also changed
from integer to 'size' e.g. 512K. This fixes the inputs and uses the
value from r2 (512K).

### CODE REVIEW

**Comment by xarkes** [comment]
I will delete the option.

**Comment by ITAYC0HEN** [comment]
Ping @xarkes. It's been a week :)

**Comment by xarkes** [comment]
Life goes fast!

**Comment by xarkes** [comment]
Don't merge I think there is something wrong.

**Pull request merged**
