### PR TITLE
Add status bar and display items count

### LINKED ISSUE #754: Show number of items in QTreeView widgets (Functions, Strings, etc.)
Naturally, we have many QTreeViews implemented for our widgets. The problem is that the user can't know how many items are shown in the widget in a given time.

image

For example, I wanted to know how many functions a binary have and I had no other option except executing `afl~?` in the Console widget.

I'd like the widgets to show me how many items (lines) there are in each widget, and this number should be changed when filtering the view (i.e to show the number of items which currently showed in the widget).

### PR DESCRIPTION
**Pull request by smhaziq**
To resolve #754 

Implemented on these widgets:
1. Comments
2. Exports
3. Flags
4. Functions
5. Imports
6. Register Refs
7. Relocs
8. Strings
9. Symbols
10. VTables

Preview:
out

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Nice, good work @smhaziq! :)
Can you please change the indicative string from "Showing items: %n" to "%n Items"?

**Comment by smhaziq** [comment]
> Nice, good work @smhaziq! :)
> Can you please change the indicative string from "Showing items: %n" to "%n Items"?

Will do. Thanks

**Comment by xarkes** [comment]
So if I understood correctly, you did copy paste that through all the widgets.
Copy pasting is usually a bad practice, I would suggest to add a `CutterTreeWidget` class that implements the counting, so you just have to modify the class definition of the ones you modified without copy pasting.

**Comment by smhaziq** [comment]
> So if I understood correctly, you did copy paste that through all the widgets.
> Copy pasting is usually a bad practice, I would suggest to add a `CutterTreeWidget` class that implements the counting, so you just have to modify the class definition of the ones you modified without copy pasting.

ok, good suggestion.
I try to avoid class change as I don't have much info on Cutter's class design.
so I need some info to refactor the code.

1. Which widget is defined as Cutter Tree Widget? For now my implementation is based on whether the widget support filtering so my classification might be incorrect.
2. Should all Cutter Tree Widget have status bar with number of items?

**Comment by xarkes** [comment]
1. There is no class for that I think
2. I think yes

**Comment by ITAYC0HEN** [comment]
> Should all Cutter Tree Widget have status bar with number of items?

Probably yes. Can't think of a reason not to. Anyway, ideally you can make the class accept boolean value (true/false) for whether to show the status bar. Moreover, it'd be best if the status bar would be flexible for other "statuses" except only number of items.

For example, after #766 will be fixed we would add the number of selected items.

**Comment by smhaziq** [comment]
Ok noted. I'll make the features configurable.
Thanks for the inputs.

**Comment by ITAYC0HEN** [comment]
please let us know when you're done so we can check things again :)

**Comment by xarkes** [comment]
It looks good, however I wonder if having it as an attribute is better than inheriting from the class.

**Comment by smhaziq** [comment]
Sorry I'm a bit busy this week and I still figuring out how the class can be consolidated with #766 .
It take more effort to design the class to control the tree view which I think is out of the scope of this task.

> It looks good, however I wonder if having it as an attribute is better than inheriting from the class.
> Maybe yes.

Ideally, I want the CutterTreeWidget class to be extended with more tree view control later, like the filtering or the selections control. But for current implementation of status bar, maybe as an attribute in CutterDockWidget is enough.

**Comment by xarkes** [comment]
So can I merge this and let @duck2 improve the class?

**Comment by smhaziq** [comment]
> So can I merge this and let @duck2 improve the class?

Yes, please. Thanks

**Comment by xarkes** [comment]
Thanks for your contribution!

**Pull request merged**
