### PR TITLE
Constant name lookup

### PR DESCRIPTION
**Pull request by mauronz**
Additional feature that allows to find the name associated to an immediate value, for example when passed to an API function. A dialog window shows the list of names associated to the selected value. When the user selects one of the names, it is added as a comment.

An example:

const

At the moment I only implemented a list of Windows constants.

### CODE REVIEW

**Comment by mauronz** [comment]
One of the Travis jobs timed out randomly while installing python packages, can someone restart it please?

**Comment by Maijin** [comment]
Oh that must not be put in cutter repo, this is a radare2 enhancement.

**Comment by mauronz** [comment]
I was thinking about that, but I'm not sure how to handle it on CLI. For some values (0, 1, ...)  there are thousands of possible names, how should we display them?

**Comment by xarkes** [comment]
Agreed, nice feature but needs to be done in radare2 :)
For additional help you can come on IRC and ask for help. Or we can try to answer your questions here. As @thestr4ng3r said, printing too many lines is not a problem in radare2.

**Comment by mauronz** [comment]
Alright then :) I'm not familiar with r2 source code, so can you point me to some "similar" feature from where I can take inspiration?

**Comment by thestr4ng3r** [comment]
Ok so we discussed a bit and came to the following conclusion:
In r2, you can already save enums. See the `te` command:
```
[0x00005000]> te?
|Usage: te[...] 
| te                 List all loaded enums
| te <enum>          Print all values of enum for given name
| te <enum> <value>  Show name for given enum number
| teb <enum> <name>  Show matching enum bitfield for given name
| te?                show this help
```
You can define enums like this:
```
"td enum elf_class {ELFCLASSNONE=0, ELFCLASS32=1, ELFCLASS64=2};"
```
then use it like this for example:
```
[0x00005000]> te elf_class 1
ELFCLASS32
```
What's different from your constants is of course that you need an enclosing enum with a name, but I think that's probably even more useful if you get some context about where this constant actually comes from.

So the main thing that is still missing from r2 is a command that searches all saved enums for an integer value, not just one like in the example above. And it will also need json output. So at first you should probably implement `tej`, i.e. just add json to `te`, then implement another command (maybe called `tes` and `tesj`? @Maijin @radare @xarkes) that only takes the one integer.
Then you basically already have the search functionality.

As a second step, we will need a way to import the data from your constants.txt (btw, where did you get that from?) into r2 as enums. But for that we don't have a clear solution yet.

**Comment by XVilka** [comment]
Related issues in radare2:

https://github.com/radare/radare2/issues/9600
https://github.com/radare/radare2/issues/6754
https://github.com/radare/radare2/issues/4508

@sivaramaaa might help in some aspects of this

**Comment by radare** [comment]
Sgtm

**Comment by xarkes** [comment]
ping @mauronz

**Comment by mauronz** [comment]
I have played around with enums, but I cannot find a feasible way to use them. The idea of using the enclosing enum as a context is good in theory but I don't know how to apply it to 40k constants. A different approach I came up with would be using a separate command. Constants can be stored in a sdb with the following structure:

```
winconst : {  
    "0" : [ NAME_0_1, NAME_0_2, ... ],  
    "1" : [ NAME_1_1, NAME_1_2, ... ],  
    ...
}
```

In this way the search is free because we can just retrieve the list of the required value.


> btw, where did you get that from?

Some lists online and some grepping/editing on the Windows SDK :)

**Comment by XVilka** [comment]
@mauronz you can put those constants into the different enums, in fact it makes them even better organized.

**Comment by mauronz** [comment]
If I'm understanding you correctly, for example with CreateFile constants there would be one enum for desired access flags, one for share mode flags, one for creation disposition flags and one for attribute flags. I can't think of a way to automatize this categorization, and doing it by hand is impossible.

**Comment by thestr4ng3r** [comment]
I think it is possible to have an enum with multiple values assigned to the same integer value. I'm not sure if this is completely intended though and commands may not support this properly right now. But if that is something that is explicitly allowed, for your case you could simple create a single enum and throw all your constants in it that you haven't manually categorized yet.
Then that db would not really be nice enough to be included in r2 by default, but the functionality would be there.

**Comment by xarkes** [comment]
ping @mauronz?

**Comment by xarkes** [comment]
ping @mauronz

**Comment by xarkes** [comment]
Closing as getting no answer.

**Comment by Maijin** [comment]
@xarkes https://github.com/radare/radare2/issues/11748 it's done now in r2

**Pull request closed without merging**
