### PR TITLE
Cmake install

### LINKED ISSUE #1896: CUTTER_ENABLE_GRAPHVIZ=AUTO fails on windows
**Environment information**
* Operating System: Windows 
* Cutter version: af5d1dd3aad38ecdf252b145a3e6f8e174ae2712
* File format: N/A

**Describe the bug**

When trying to do a cmake build on windows automatic graphviz detection fails due to FindPkg not being available. Manually forcing CUTTER_ENABLE_GRAPHVIZ=OFF avoids the problem.

**Expected behavior**

If FindPkg is not available behave the same as when FindPkg is available but it can't find Graphviz.

### LINKED ISSUE #1914: Install headers to global includes folder
**Is your feature request related to a problem? Please describe.**

By now, all header files won't be installed into system path (like `/usr/include` for example) so if any plugin has to compile the source code, it needs Cutter source code (the whole project code)

**Describe the solution you'd like**

Install headers in `/usr/include` or whatever system has so plugins can use the headers to compile the source (as same as current radare2 i believe)
**Describe alternatives you've considered**

Debian packaging should set the `libradare2-cutter-dev` or something like that for the header

**Additional context**

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**
First steps towards CMake install (maybe in combination with cpack) being usable for packaging Cutter.

**Test plan (required)**
* make sure compilation on old Ubuntu still works, CMake install support is optional :heavy_check_mark: 

Test install on Windows using Bundled radare2. ✔️ 
* Build using CMake and bundled r2
* test that Cutter in Build directory opens and r2 resources (color themes, greetings, ...) are loaded
* repeat previous step in install directory (requiring manual Qt copying is acceptable)

 Test make install on Linux, recommended doing in a VM. :heavy_check_mark:*

* install r2
* build Cutter using system r2
* `sudo make install`
* make sure executable is installed in correct place
* make sure Cutter executable opens and there are no dynamic library loading errors
* make sure r2 resources  (color themes, greeting messages, ..) are found
* make sure Desktop environment finds the .desktop file, Cutter shows up in list of programs with correct icon
* make sure the icon gets used when Cutter executable is running
* test that installed Cutter dev files can be used for compiling plugins by compiling Cutter Ghidra plugin externally 

\* Compiling r2ghidra requires fresh CMake so the plugin compilation part couldn't be tested with Ubuntu 18.04 default CMake. It was also necessary to remove FindCMake because find_package prefers FindCMake.cmake over the installed cmake config unless CMAKE_FIND_PACKAGE_PREFER_CONFIG option is used. GHidra plugin will need to be updated, the old mechanism can't be removed until official releases are built using new mechanism.

**Known limitations**
When using with CUTTER_USE_BUNDLED_RADARE2=ON doing `make DESTDIR=foo install` directly instead of `make` and `make install separately` affects r2 meson output directories thus breaking the build.

**Follow up tasks**
* translation installation
* Python bindings and Python file installation for Windows, Appimage, macOS packages
* Bundled plugin installation (r2ghidra, r2-dec)
* macOS file installation
* ~plugin compilation on windows~ export annotation

**Closing issues**

closes #1896 
closes #1914

### CODE REVIEW

**Comment by karliss** [comment]
TODO:
* [ ] CUTTER_USE_BUNDLED_RADARE2=OFF
* [ ] Preserve Cutter header folders
* [ ] External plugin compilation testing
* [ ] Older CMake compatibility testing

**Comment by karliss** [comment]
I will do the Windows part of test plan tomorrow.

**Comment by karliss** [comment]
Tried compiling r2ghidra-dec using the cutter and r2 files from install file. I was able to get configure working and compilation working. Linking to Cutter executable failed will need to investigate that.  Command used was
```
cmake -DBUILD_CUTTER_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=./idir 
-DCMAKE_TOOLCHAIN_FILE=path_to_vcpkg\vcpkg\scripts\buildsystems\vcpkg.cmake
-DCMAKE_PREFIX_PATH=cutter_install\lib  -DRadare2_INCLUDE_DIRS=cutter_install\include\libr\
-DRadare2_LIBRARY_DIRS=cutter_install\lib ..
```
In addition FindCutter.cmake was removed the same as on linux, changed find_library call in FIndRadare2.cmake.

**Comment by karliss** [comment]
Got the Plugin compilation on windows working as well. Committed part of changes in e9eac3f, but it will also require adding `CUTTER_EXPORT` annotation in headers expanding to `__declspec(dllimport)` and `__declspec(dllexport)`. Since it will require modifying large amount of files I would prefer doing it in separate PR. Most of the code is in classes and there are few freestanding functions so there won't be as much changes as if Cutter had C API.

**Comment by ITAYC0HEN** [comment]
Good job @karliss !! 
should the docs be updated?

**Comment by karliss** [comment]
@ITAYC0HEN The install part isn't ready for use yet but bundled radare2 on windows  should be added to the main windows instructions.

**Pull request merged**
