### PR TITLE
Toggle the address maps in the Section Widget

### PR DESCRIPTION
**Pull request by Vane11ope**
gifrecord_2018-11-25_172116

Adding a toggle button to the address maps in the Section Widget. Check the gif.

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Looks good!
Can you please make a 90degrees rotation to the arrow so it would point upwards?

**Comment by Vane11ope** [comment]
@ITAYC0HEN  sharp eyes(i did not mean to test you). the thing is if I could just add the rotated picture to the folder or you want me to solve it in code, as it seems little complicated to do the latter.

**Comment by ITAYC0HEN** [comment]
programmatically please

you probably can use QTransform and maybe QPixmap. Should be 2-3 more line.
Also, please comment a description for this above these line so other devs would be able to search for this example in the code

**Comment by ITAYC0HEN** [comment]
Thank you <3

**Pull request merged**
