### PR TITLE
Add Ctrl-Shift-C shortcut

### LINKED ISSUE #1474: Add Copy Address shortcut in hexdump
**Is your feature request related to a problem? Please describe.**

To be able to quickly copy the current address

**Describe the solution you'd like**

(<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>) - will copy the address where the cursor is

### PR DESCRIPTION
**Pull request by TheLorax**
Copy current address in disassembly and graph mode

**Test plan (required)**
Hit Ctrl-Shift-C in either graph or disassembly view and paste the address elsewhere.

**Closing issues**

Closes #1474

### CODE REVIEW

**Comment by Maijin** [comment]
@TheLorax Did you try it in the hexdump panel too?

**Comment by TheLorax** [comment]
Didn't think of that. It doesn't work in hexdump.

**Comment by Maijin** [comment]
Ok then this doesn't fix the issue

**Comment by Maijin** [comment]
Wait why did you close? That was correct for the  disassembly and graph so we could have merged that :/

**Comment by TheLorax** [comment]
I'll make it work for both :)

**Comment by Maijin** [comment]
ok great!

**Pull request closed without merging**
