### PR TITLE
Correct "Rename function" in menu

### LINKED ISSUE #887: Correct `Rename function` menu
**Environment information**
* Operating System: Parrot OS 4.2
* Cutter version: git, pulled 29/10/2018
* File format: ELF 64

**Describe the bug**
`Rename function` in `Graph panel` menu displayed `(used here)` (rename it in local function) but it renames function globally.

**To Reproduce**
1. Right click on function -> choose `Rename function (used here)`
screenshot at 2018-10-30 16-31-59

2. Click on `Rename function` and rename it
screenshot at 2018-10-30 16-32-22

3. Submit result. Now function name has been renamed globally
screenshot at 2018-10-30 16-32-37

**Expected behavior**
`Rename function` line in menu does not have `(used here)`

**Additional context**
`Rename function` and `Rename variable` are using same condition to display text.

### PR DESCRIPTION
**Pull request by dmknght**
**Closing issues**

closed #887

### CODE REVIEW

**Comment by dmknght** [comment]
Fixed #887

**Comment by dmknght** [comment]
closes #887 ;

**Comment by dmknght** [comment]
closes #887 ; Correcting "Rename function" display in menu

**Comment by dmknght** [comment]
Did it work? This thing is so complicated.....

**Comment by mohe2015** [comment]
@dmknght It already worked in your first comment which you can see by the dotted underline. If you hover over it it shows: "This pull request closes issue #887"
The issue will be closed if this pull request is merged.

**Comment by dmknght** [comment]
Ahh i've noticed that `}`. Very sorry about that. I am using github web interface. Is it good now? I've fixed it.

**Comment by xarkes** [comment]
Yes, thank you :)

**Pull request merged**
