### PR TITLE
append layout to OpenFileDialog, so the dialog more flexible

### PR DESCRIPTION
**Pull request by ncyellow**
when resizing the OpenFileDialog is looks terrible. 

old

so i added layout  and change align "Select Button" and the widget looks better.

select button align

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Thank you, good catch! Appreciate it a lot and it sure much better than we have now.

If you allow me, I will suggest even another modification.
Can you please order the components in three columns? 

Column #1: "File:" and "Map address:" -- Not expandable, keeps it size and location to the left border
Column #2: both Text boxes -- expandable
Column #3: The Select File button

So upon expanding, only the textboxes would expand, and everything would look more symmetric

**Comment by ncyellow** [comment]
image


> Thank you, good catch! Appreciate it a lot and it sure much better than we have now.
> 
> If you allow me, I will suggest even another modification.
> Can you please order the components in three columns?
> 
> Column #1: "File:" and "Map address:" -- Not expandable, keeps it size and location to the left border
> Column #2: both Text boxes -- expandable
> Column #3: The Select File button
> 
> So upon expanding, only the textboxes would expand, and everything would look more symmetric

image

**Comment by ncyellow** [comment]
> Thank you, good catch! Appreciate it a lot and it sure much better than we have now.
> 
> If you allow me, I will suggest even another modification.
> Can you please order the components in three columns?
> 
> Column #1: "File:" and "Map address:" -- Not expandable, keeps it size and location to the left border
> Column #2: both Text boxes -- expandable
> Column #3: The Select File button
> 
> So upon expanding, only the textboxes would expand, and everything would look more symmetric


like this?
select button align

**Comment by ncyellow** [comment]
> Thank you, good catch! Appreciate it a lot and it sure much better than we have now.
> 
> If you allow me, I will suggest even another modification.
> Can you please order the components in three columns?
> 
> Column #1: "File:" and "Map address:" -- Not expandable, keeps it size and location to the left border
> Column #2: both Text boxes -- expandable
> Column #3: The Select File button
> 
> So upon expanding, only the textboxes would expand, and everything would look more symmetric

like this?
3 column

**Comment by ITAYC0HEN** [comment]
Very very good! Thank you!

**Pull request merged**
