### PR TITLE
Disable Homebrew Update on Travis

### PR DESCRIPTION
**Pull request by thestr4ng3r**
to be merged when travis is fixed
https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798

### CODE REVIEW

**Comment by xarkes** [comment]
Can we merge now that Travis is green?

**Comment by karliss** [comment]
@xarkes No, It is currently green due to a workaround and this PR removes that workaround. We have to wait until Travis update their VM.

**Comment by xarkes** [comment]
Oh ok my bad, for some reason I thought Travis did that already.

**Comment by karliss** [comment]
Supposedly xcode10.2 image contains newer Homebrew. Can we use that?

**Comment by thestr4ng3r** [comment]
Yes, why not? Feel free to push to this branch.

**Comment by xarkes** [comment]
According to the linked thread, 10.2 fixed it.

**Comment by karliss** [comment]
Hmm, it fixes homebrew but causes different problem.

**Comment by xarkes** [comment]
Is it https://github.com/radareorg/cutter/issues/1440?
It looks like the bindings cannot compile from the logs.

**Comment by karliss** [comment]
The new error could be caused by https://travis-ci.community/t/xcode-headers-not-installed-since-osx-10-14/4286 .

**Comment by karliss** [comment]
Finally green, reduces build time by 10-15 minutes.

**Comment by thestr4ng3r** [comment]
Nice, thanks a lot!

**Pull request merged**
