### PR TITLE
LGTM Config

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by xarkes** [comment]
Ah sorry I didn't see your PR, I also update that PR with it: https://github.com/radareorg/cutter/pull/1535
I can remove it from my PR and merge this one if you prefer.
Also I am not sure but I think you have to remove the `/` in front of the name of the library.

**Comment by thestr4ng3r** [comment]
Yeah let's see if it works

**Comment by thestr4ng3r** [comment]
Doesn't work. I don't get it.

**Comment by thestr4ng3r** [comment]
But it's definitely more correct than the version on master, so I'll merge and see if that changes anything.

**Pull request merged**
