### PR TITLE
Disabled QtWebEngine by default.

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by Maijin** [comment]
do it

**Comment by XVilka** [comment]
Can you please still build both on AppVeyor and Travis?

**Comment by Maijin** [comment]
No that's where the issues are coming from, let's kill this. The jupyter is still here, it's only removing the webengine.

**Comment by XVilka** [comment]
Jupyter doesn't work without WebEngine, no?

**Comment by Maijin** [comment]
It does 👍 It just that instead of having it as a "tab" it will just be available from the browser of the user itself

**Comment by XVilka** [comment]
Which is a crap. As a user I hate this UX. I don't know about others, this
is not for me.

**Comment by xarkes** [comment]
I think you love too much Jupyter.
Imho we should better have custom widgets (made in Python or C++ as you wish) as plugins, rather than keeping Jupyter.
I don't like the QtWebEngine because 1) It's heavy (binary size) 2) It spawns many threads (heavy to start) 3) Currently, it produces segfaults with the threads from r2 4) It's overkill 5) I don't like HTML and Electron applications, I see no reason to have it. 6) I hate duplicating chromium while you already have it running... Just add a tab, rather than a whole Chromium process.

Anyway, if you want to have QtWebEngine, clone the repository and set `CUTTER_ENABLE_QTWEBENGINE=true` in the `Cutter.pro`.

**Comment by XVilka** [comment]
Jupyter is not only about widgets - it is mostly about:
 - analysis of the data
 - sharing the notes between researchers in one team

**Comment by xarkes** [comment]
Yes, for now, as far as I know, none of this is available in Cutter.
So I don't see the problem to remove the web engine (and still allow usage of Jupyter) for now.
It's not necessarily definitive.

**Comment by xarkes** [comment]
> As a compromise: Add information about reenabling QtWebEngine in the README?
And yes this will be pointed in the documentation (we are currently rewriting it).

**Pull request merged**
