### PR TITLE
Replace hardcoded system plugin directories with list from Qt.

### LINKED ISSUE #1783: Create a global plugin path
**Is your feature request related to a problem? Please describe.**

I am packaging cutter for Parrot OS with pre-installed ghidra decompiler. However the current appdir path is in `$HOME` folder which isn't supported by debhelper (from the docs i read online). I think i can change the `appdir` flag of cutter but it looks like cutter won't use $HOME path to read plugins in the future so users can't install plugin with user permission. I think this way will very friendly for Debian packaging.

**Describe the solution you'd like**
Create a global path for plugin and an other path in `$HOME`. It should be like vim:
- `/etc/vimrc` is the global path
- `$HOME/.vimrc` is the local path of user

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**

* Replace hard-coded system plugin directories with use of `QStandardPaths` it should return the same values as what was used before but with less platform specific code in Cutter.
* Potentially simplify support of new platforms supported by QT
* Supports gobal plugin directories on Linux. Locations chosen by Qt with any modifications done by distro maintainers.
* Build option to specify additional plugin directories for more pedantic package maintainers that think that plugins are not data.

**Test plan (required)**

* Run on Linux, macOS, Windows and verify that printed paths console output indicates attempts to load from correct directories
    * Linux :heavy_check_mark: 
    * Windows - :heavy_check_mark:  tested by yossizap
    *  macOS - help wanted
* Run AppImage and test that plugins packed inside AppImage are loaded :heavy_check_mark: 

**Closing issues**

Closes #1783

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
is this still a wip/draft?

**Comment by karliss** [comment]
I need to test how it interacts with Appimage and if I can remove the special case for that.

**Comment by xarkes** [comment]
What are the paths used on linux?

**Comment by karliss** [comment]
@xarkes  See https://doc.qt.io/qt-5/qstandardpaths.html

**Comment by xarkes** [comment]
Okay so `~/.local/share/<APPNAME>`.

**Comment by karliss** [comment]
"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"

The first one as user plugin directory, and the rest for system plugins either packed together with cutter or installed through system's package manager.

**Comment by im-0** [comment]
> "/usr/local/share/", "/usr/share/"

This does not look like a sane path to put "system-wide" plugins on Linux.

Usual place for native (*.so) plugins is either `/usr/lib/$APPNAME/` or `/usr/lib64/$APPNAME` (depending on architecture). And for python plugins it is probably `/usr/lib/python$PYTHONVERSION/site-packages/$APPNAME/` (not an expert here, just saw few applications doing this).

And the best way to implement this is to provide some compile-time option to specify these paths. Otherwise package maintainers will really hate you =).

**Comment by karliss** [comment]
I meant `"~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"`   github ate the angle brackets.  As explained before those paths are coming from Qt:StandardPaths according to qt configuration.

**Comment by karliss** [comment]
Finally prepared a setup for building appimage. Looks like it doesn't need manual handling as well. Now I have to rebuild it again.

**Comment by karliss** [comment]
Had to leave the special case for APPIMAGE. Qt doesn't handle that.

**Comment by yossizap** [comment]
Ran in Windows:

```
Plugins are loaded from "C:/Users/User/AppData/Roaming/RadareOrg/Cutter/plugins"
Loaded 0 plugin(s).
Plugins are loaded from "C:/ProgramData/RadareOrg/Cutter/plugins"
Plugins are loaded from "C:/workspace/cutter/build_x64/cutter/plugins"
Plugins are loaded from "C:/workspace/cutter/build_x64/cutter/data/plugins"
Plugins are loaded from "C:/workspace/cutter/build_x64/cutter/data/RadareOrg/Cutter/plugins"
```

Anything else?

**Comment by thestr4ng3r** [comment]
macOS:
```
florian-macbook:~ florian$ /Applications/Cutter.app/Contents/MacOS/Cutter
Cutter Launch Script for macOS 🥞
Setting PYTHONHOME = "/Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/Current"  for macOS Application Bundle.
PYTHONHOME = "/Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/Current"
Setting r2 prefix = "/Applications/Cutter.app/Contents/Resources/r2"  for macOS Application Bundle.
Setting r2 plugins dir = "/Applications/Cutter.app/Contents/Resources/r2/share/radare2/plugins"
Not loading library because it has already been loaded from somewhere else: '/Users/florian/.local/share/radare2/plugins/core_ghidra.dylib'
Plugins are loaded from "/Users/florian/Library/Application Support/RadareOrg/Cutter/plugins"
Load Error for plugin "libr2ghidra_cutter.dylib" : "The plugin '/Users/florian/.local/share/RadareOrg/Cutter/plugins/native/libr2ghidra_cutter.dylib' uses incompatible Qt library. (5.13.0) [release]"
Loaded 0 plugin(s).
Plugins are loaded from "/Library/Application Support/RadareOrg/Cutter/plugins"
Plugins are loaded from "/Applications/Cutter.app/Contents/Resources/plugins"
Loaded 1 plugin(s).
```

**Comment by xarkes** [comment]
Alright, let's merge?

**Pull request merged**
