### PR TITLE
Adding a header to the DisassemblyWidget to show the function prototype

### LINKED ISSUE #125: Add prototype of function
Add prototype of function in display, requires https://github.com/radare/radare2/issues/8785

### PR DESCRIPTION
**Pull request by Vane11ope**
Fix #125 

gifrecord_2018-10-07_074834

### CODE REVIEW

**Comment by xarkes** [comment]
We discussed it on Telegram, I don't remember what was decided?
cc @Maijin @thestr4ng3r @ITAYC0HEN

**Comment by Maijin** [comment]
@ITAYC0HEN will provide guidance for the refinement

**Comment by Maijin** [comment]
Yeah sounds good

**Comment by Vane11ope** [comment]
done

**Comment by Vane11ope** [comment]
This is how it looks and works like
gifrecord_2018-10-16_231024
screenshot from 2018-10-16 23-07-14
screenshot from 2018-10-16 23-06-48

**Comment by ITAYC0HEN** [comment]
Thank you @Vane11ope! Well done :)

**Comment by xarkes** [comment]
Are you using the same colors as in r2? `func_var` `func_var_type` and `func_var_addr`?

**Comment by ITAYC0HEN** [comment]
Colors are generated by `QSyntaxHighlighter`. These are the same colors used at r2dec widget iirc.

**Pull request merged**
