### PR TITLE
Add more breakpoint editing options

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**
* Convert breakpoint widget to AddressableItemWidget
* When selecting multiple breakpoints and pressing delete key delete all of them
* Allow toggling breakpoint trace and active properties by doublicking them in table

**Test plan (required)**

* start debuging
* Create a few breakpoints
* doubleclick a breakpoint in breakpoint widget, make sure seek works
* rightclick an item in breakpoint widget,  it should contain actions from AddResableItem widget, and toggle, delete actions.
   * test at least one AddressableItemWidget action using menu and keyboard shortcut
   * test that toggle using space and menu works
* test that deleting single breakpoint works (using menu, button, keyboard)
* test that deleting multiple selected breakpoints work

Part2
* start debuging
* create 3 breakpoints
* disable first one by double clicking "active" column
* enable trace mode for second breakpoint by double click in trace column
* verify that breakpoint state reported by `dbj` matches previous actions
* resume executable by pressing continue
* make sure debugger stops on third breakpoint and printed trace message for second one

**Observed issues**
Changing trace property for first breakpoint doesn't work. Due to r2 sharing logic for handling address and index argument in db command. Need to create an issue for that.

When breakpoint is disabled it is still triggered and printed in console, but automatically continued. Not sure if this is intended behavior or not. I expected disabled breakpoint not to be triggered at all. What happens when it has command asigned?

**Closing issues**

### CODE REVIEW

**Comment by karliss** [comment]
Test plan completed.

**Comment by karliss** [comment]
1. It is triggering a full reload which causes loss of focus. It shouldn't be difficult to avoid that.

2.I don't think it's necessary.  x64dbg doesn't ask either.

> weird. Do you know if the memory is changed to int3`CC`? because if so, it is problematic

I think they do. All the other mechanisms that I can think of for them being triggered and printed in console would be even worse.

**Comment by ITAYC0HEN** [comment]
so (1) should be fixed probably and (2) is fine to keep as is. 

>I think they do

that's problematic. I don't understand why. Because it happens a lot that malware is using anti-debug tricks in which they check their memory for CC instructions. So in order to avoid this, analysts usually disable their breakpoints in the ant-debug function and restore them when finish. Keeping the CC on disabled device is meaningless. In x64dbg, iirc you can set "action" for the bp and tell it specifically to do-nothing when reaching it, only log, or run command. But when disabled it should be disabled for real

**Comment by karliss** [comment]
@yossizap Keyboard shortcut ambiguity needs to be fixed. What other widgets did you have opened?

As for additional suggestions they are more or less in the spec.

**Comment by yossizap** [comment]
>What other widgets did you have opened?

Default debug widgets + processes + flags. Seems that closing flags solved the issue.

**Pull request merged**
