### PR TITLE
Make graph highlight darker on light themes

### PR DESCRIPTION
**Pull request by Adikso**
Change:

To:

On light themes

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Thanks for the PR! :)

TBH, I'm not a fan of the gray. 
Althought not perfect, but I would go for something like this:

```
QColor selectionColor = disassemblySelectionColor.blue() > 160 ? QColor(179, 119, 214, 70) : 
                                                                 QColor(250, 221, 255, 50);

```

**Results:**

image

image

**Comment by Adikso** [comment]
What if I would like to have pretty pink GU :C? 

But yes.. my idea is not that perfect too

**Comment by ITAYC0HEN** [comment]
ping @Adikso,
let's go for the best color version we have which is this
:
```
QColor selectionColor = disassemblySelectionColor.blue() > 160 ? QColor(179, 119, 214, 70) : 
                                                                 QColor(250, 221, 255, 50);
```

And you're totally right for the edge cases with the background color, but this can be improved as we go.

Can you modify the PR and push? I'll merge

**Comment by Adikso** [comment]
You wrote nearly the whole code in a comment. You could commit this change yourself ;)

**Comment by ITAYC0HEN** [comment]
Sorry @adikso, didn't want to offend by overtaking your pull request and idea. Sent a PR myself now. Thank you again

**Pull request closed without merging**
