### PR TITLE
Debug support

### PR DESCRIPTION
**Pull request by xarkes**

### CODE REVIEW

**Comment by pelijah** [comment]
Cutter stops responding after clicking the "Stop Debugging" button (at least on Windows).

**Comment by xarkes** [comment]
@pelijah That's due to a bug in r2.

**Comment by fcasal** [comment]
@pelijah I believe the issue is fixed now if you would like to try it

**Comment by XVilka** [comment]
So, what with this one?

**Comment by xarkes** [comment]
As discussed before there are two remaining issues:

1. Cutter hangs/crashes when its r2 core hangs/crashes, even when the r2 cmd is launched from the console widget (which use the tasks).
2. In linux you can only PTRACE a thread from ONE tracer thread. This means that we can't have the console widget commands going through the threaded tasks unless we either change how debugging works in r2 or disable tasks during debug.

**Comment by xarkes** [comment]
Requires https://github.com/radare/radare2/pull/11723

**Comment by xarkes** [comment]
Will reopen when support is better.

**Pull request closed without merging**
