### PR TITLE
Center rename dialogs

### LINKED ISSUE #1735: Rename dialog is opened on the top-left corner of the screen
**Environment information**
* Operating System: Windows
* Cutter version: Current Master
* File format: Any

**Describe the bug**
The Rename dialog is opened in the corner of the screen.

**To Reproduce**

Choose a label/flag/function and rename it using <kbd>N</kbd> or <kbd>Shift</kbd>+<kbd>N</kbd>. See that the dialog is in the corner

**Expected behavior**
Should get open in the middle of the parent\screen

**Screenshots**

image

**Additional context**
Similar to #1337

### PR DESCRIPTION
**Pull request by ITAYC0HEN**
**Detailed description**
This PR makes sure that the Rename dialogs will open in the center of the screen and not in the corner.
The solution is based on #1384 by @AntonReborn .

**Test plan (required)**
Choose a flag in the disassembly and click <kbd>Shift</kbd>+<kbd>N</kbd> to open rename diaolog.
Notice how it is now opened on the center.

**Closing issues**

closes #1735

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Doesn't this prevent the dialog from always being on top of the MainWindow and making it un-focusable (which would be desired probably)?

**Comment by karliss** [comment]
Wouldn't it be more correct to set the main window as parent for modal dialog?
I guess some of the current weirdness comes from setting a context menu which closes as parent for modal dialog. At least for me it fixed the centering problem and even enabled tracking.

**Comment by thestr4ng3r** [comment]
Yes, this sounds much better

**Comment by ITAYC0HEN** [comment]
So should i access the "main" variable and set it as parent? I think it's feasible

**Comment by thestr4ng3r** [comment]
Yes. It's `mainWindow` in the DisassemblyContextMenu class I think.

**Pull request merged**
