### PR TITLE
Add more graph widgets

### LINKED ISSUE #406: Add Call-Graph
Add Call-Graph

### LINKED ISSUE #1776: agC Global callgraph, but with cutters graph engine
I really like cutters overview and graph views for functions.

It would be super useful to have an interactive version of the agC command to help spelunk overall code organization of a binary!

How easy would it be to tap into the whole family of ag* graph commands and provide native cutter views for them?

### LINKED ISSUE #2178: Generic r2 graph widget
**Is your feature request related to a problem? Please describe.**

R2 has many graph types. When r2 adds new one it can't be viewed using dedicated graph widget until Cutter adds support for it.

**Describe the solution you'd like**

Generic graph widget widget can display any of r2 graphs (as long as they use existing interface). User must be able to select the graph any of r2 graphs without having hard coded list in Cutter. This could be done by allowing user to specify r2 command which prints desired kind of graph.

Difference between this and #2177 is that this will be able to display any future r2 graphs just by just linking Cutter against newest r2.

Widget should support the same features existing basic block graph has:
* panning and zooming
* export graph using r2 command (gml, json, dot, dot->image)
* export the image drawn by Cutter

**Describe alternatives you've considered**

#2177 dedicated graph widgets

**Additional context**

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Introduce generic r2 graph widget. User can select one of the r2 graph types in the list or enter a command. Since it executes more or less arbitrary r2 command it needs to be manually refreshed using a button.

Add a specialized CallGraphWidget  used for global and single function callgraph. Extra features in the callgraph widget compared to generic one:
* works with callgraph,  agc can't be used in the generic widget because agcj and agCj doesn't have the same structure as rest of ag*j commands
* addressable item context menu when clicking on a block
* seek synchronization
* show in Callgraph and show in Global Callgraph when in addressable item context menu for other widgets

Expose more graphviz layout engines(sfdp, neato, twopi, circo), might be useful for some of the reference graphs.

GraphGridLayout bugfix for a case with multiple top level blocks. Almost never happens for CFG but is somewhat common in callgraph and some of other r2 graphs

Fix the false dock showing causing RefreshDeferrer to work poorly. This was probably a regression caused by dock layout switching feature. 

Code refactoring and other changes:
* split some of the MemoryDockWidget into AddressableDockWidget
* Introduce CutterGraphView for some of the common Cutter specific logic like styling, reading config values, and reaction to Config and Core events. GraphView base shouldn't contain any Cutter specific code to make it easier sharing code with x64dbg . Move some of the logic from DisassemblerGraphView to it now that there are other graphs to share it with.
* new class SimpleTextGraphVew for graphs consisting of plaintext label and optionally address associated with each block

**Test plan (required)**

Screenshot from 2020-07-10 14-33-23
Screenshot from 2020-07-10 14-33-37
Screenshot from 2020-07-10 14-35-24
show_in_context_menu
Screenshot from 2020-07-10 14-35-44
Screenshot from 2020-07-10 14-35-03

Steps
* Test show in Callgraph: right click in function widget, select show in Callgraph  :heavy_check_mark: 
* Test show in Global Callgraph: right click in function widget, select show in Global Callgraph  :heavy_check_mark: 
* Callgraph position synchronization:  :heavy_check_mark: 
    * Click at different functions in disassembly widget, make sure both callgraphs are updated accordingly  :heavy_check_mark: 
    * Disable synchronization and click in disassembly widget make sure callgraphs are not updated  :heavy_check_mark: 
* Image export  do the steps for both callgraphs and at least one graph in the generic r2 graph widget :heavy_check_mark:*
    * Direct png export, check the large bitmap warning using one of global graphs
    * Direct svg export
    * Json export
    * graphviz based image export
    * gml export
* Copy text :heavy_check_mark: 
* Copy address from callgraph :heavy_check_mark: 
* Show xrefs in callgraph  :heavy_check_mark: 
* Change layout in all new graphs * 
* Test all the new graphviz layouts (using medium size or small graph, some of them are slow) :heavy_check_mark: 

**Closing issues**

Closes #2178
Closes #406
Closes #1776

### CODE REVIEW

**Comment by karliss** [comment]
Problems found during testing:
* sometimes switching between vertical and horizontal layout in global callgraph  view gets stuck above the content.
* default export names aren't used properly

**Comment by karliss** [comment]
Both fixed.

**Comment by xarkes** [comment]
Do you have any idea of what's wrong with Travis and Appveyor?

**Comment by karliss** [comment]
Appveyor should be fixed by meson version PR that was just merged. On Travis the macOS build times out. Recent successful builds take 43-48 minutes which isn't too far from 50 minute limit.  The annoying part is that ~20 minutes out of that is taken by homebrew update which we have to do because Travis isn't updating their macOS images. See https://github.com/radareorg/cutter/pull/2077 .

**Comment by xarkes** [comment]
Things noticed while testing:
- The field name of the dropdown menu of the `R2 graphs` widget is editable
- There is no margin at all between edges so it might generate funny graphs (see picture attached below)
- `agg` seems to be useless (and that might be by design as it is named "custom") but it might be interesting to add more info or a warning or something...

image

**Comment by karliss** [comment]
> The field name of the dropdown menu of the R2 graphs widget is editable

That's by design you can enter a plain r2 command there. See description of #2178 . Idea is that even when we have dedicated widgets for all graphs a new r2 version might add new graph types. In such situation you can just type the command of new graph without waiting until new widget gets added to Cutter.

> There is no space at all between edges so it might generate funny graphs (see picture attached below)

As the amount of connected edges increases space is reduced. In my opinion that's better than keeping fixed spacing and having the ends not connect to block and spanning across multiple screens.

>  agg seems to be useless (and that might be by design as it is named "custom") 

There some use-cases for agg. One is commands like ".axg*" which store the resulting graph in "custom graph". So instead of running axgv and obtaining unreadable graph in console widget you can run ".axg*" and then opening agg in the r2 graph widget. Other potential usescase is for display graphs generated by user scripts. The same could be done by making a Cutter plugin which reuses some of Cutter graph classes, but the r2 command interface is somewhat simpler than Cutter API and such script could be run either in plain r2 or Cutter.

**Comment by xarkes** [comment]
Ok thanks for the details :) LGTM!

**Pull request merged**
