### PR TITLE
Select highlighted variable in EditVariablesDialog if possible.

### LINKED ISSUE #1726: Take hint from curHighlightedWord when renaming stack variables
**Is your feature request related to a problem? Please describe.**

Current process of renaming stack variable is:
* open "Re-type function local vars"
* find the variable in combobox
* type the new name

Step 2 is somewhat inconvenient if you have function with more than 2 variables and the similar default names don't help.

**Describe the solution you'd like**

Use curHighlightedWord as a hint for EditVariablesDIalog of which variable should be selected.

**Describe alternatives you've considered**

There are a couple of other issues related to working on selected word. It would be nice to have a more robust solution  for understanding what is selected that doesn't rely on string matching but suggestion above seems like a very simple way of making Cutter much nicer to use.

**Additional context**

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**

See #1726 for description.

**Test plan (required)**

* rename stack variable in function with multiple of them after clicking on it's name in mov instruction
* rename variable after clicking in the block at top of function
* rename register argument in the block at top of function
* rename register argument after clicking the name in function signature
* open EditVariablesDialog with no variable selected , rename after selecting variable from combobox
* open EditVariableDialog in a function without any stack variables and arguments

**Closing issues**
Closes #1726

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Looks great, an improvement indeed. I think that we still need a simply <kbd>N</kbd> shortcut or <kbd>Shift</kbd>+<kbd>N</kbd> to quickly rename a var (without setting a type). Like, pressing a shortcut, start typing and <kbd>Enter</kbd> and that's it.


And for the test case:

> open EditVariableDialog in a function without any stack variables and arguments

All combo boxes should probably be disabled with "N/A" or something similar. Empty combo boxes are useless, confusing and cause extra meaningless steps by the user. 
image

**Comment by karliss** [comment]
@ITAYC0HEN 
N - currently doesn't work due to #1698 . As for quickly renaming variable 'y' almost works like that. After opening the dialog it focuses on name field and pressing enter after changing it confirms and closes the dialog. Only problem is with selecting the right token in disassembly, there is currently no consistent way of doing that using only keyboard. As we add more selection based actions to disassembly widget the selection shortcuts should probably be improved.

What do you think of not opening the variable editing dialog if there are no variables unless we add a "add new variable" button there?

**Comment by ITAYC0HEN** [comment]
That sounds goos to me

**Comment by karliss** [comment]
@xarkes  I assume you meant the type in list of variables at top of function. That would be better, but I don't think it can be easily done. Having a more structured information about disassembly would be nice for various context sensitive actions. I really don't want to do dirty string matching hacks. The fact that whole function header block is single "line" doesn't help.

**Pull request merged**
