### PR TITLE
Add addressable item context menu to stack widget

### PR DESCRIPTION
**Pull request by karliss**
**Detailed description**

Use addressable item context menu in stack widget. Allow acting both on stack position and value pointed by pointer on stack.

Respect value editing directly in table. Previously it allowed editing the values but changes were ignored.

**Test plan (required)**

* Start emulator
* Edit a value using context menu
* Edit a value cell in table (use double click or f2 to enter edit mode), confirm with enter
* Try editing a value in table again, confirm that it is possible to enter edit mode
* Right click on offset cell, click xrefs and confirm that address is correct
* Right click on one of edited values, confirm that address is correct using xrefs
* Open context menu using menu key on keyboard, confirm target address
* Test that shortcuts work by clicking on cell and pressing 'x' for xrefs, try both offset and value column

**Closing issues**

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Overall looks good. I really like the fact that one can use flags and math operations and r2 will calculate the address.

 things I noticed --

1. Double click on a stack address will first seek to this address, another double click will ener the edit mode. If Cutter is already seek to this address, the first click will enter edit mode.
Peek 2019-09-21 10-57

2. Clicking on a cell and start typing will enter edit mode. This without pressing f2 or double clicking.
Peek 2019-09-21 11-02

**Comment by karliss** [comment]
1.  Is probably slightly unexpected interaction of reacting to double click and double click being one of indicators for entering edit mode. Result isn't too bad. I could be convinced that it's intentional.
2. Qt allows configuring multiple ways for entering edit mode. By default most of them are enable. I don't see a reason to change it unless it interferes with other functionality or there is high risk of confusion.

**Comment by ITAYC0HEN** [comment]
1. problem is that the user should understand it, otherwise they might get confused why some times it work but sometimes it triggers a seek. Also, it seeks to addresses outside of the mapped binary so this is another problem. if I have a stack value of 0x41 I don't expect cutter to seek there. 

2. only issue is that we don't have "undo" so it might be of a problem if someone is accidently rewriting a value. the f2/context menu makes sure that at least the user explicitly asked to change th value. another thing is, that global and local shortcuts (f, x) will trigger the shortcut and will not begin editing. this is again confusing, especially in the long term where we will add more shortcuts.

**Comment by karliss** [comment]
Both arguments sound reasonable. For 1. What's more important seeking or editing? I would expect seeking to return address being a common operation.

**Comment by ITAYC0HEN** [comment]
I think that seeking is the most probable one. at least that what I'd expect. In the near-future, I hope to change the way the stack\regs widgets look like and make them looks less like a table. Then it would be more clear

**Comment by karliss** [comment]
If you accidentally start editing value esc key works,  still disabled double click and any key edit triggers.

**Comment by ITAYC0HEN** [comment]
sounds good.
I have one thing though, about the seeking in hexdump. 
I prefer having it "smart" to know if this address contains code or data. and I think in general it is a good way to differ between them. code should be displayed in disassembly while data or allocated memory

having a generic, smartest, function to have it would be nice. what do you think? 
https://github.com/radareorg/cutter/issues/1736

**Comment by karliss** [comment]
In general I agree that it would be useful, but I would say it's out of scope for this issue.
Also in this specific case stack is very unlikely to contain code.

**Comment by ITAYC0HEN** [comment]
yeah might be outside the scope rewlly.
stack contains frames and return addresses

**Comment by xarkes** [comment]
So should we merge it?
The current behavior looks fine to me.

**Pull request merged**
