### PR TITLE
Rename "Color Theme" to "R2 Theme" in Appearance Options dialog

### PR DESCRIPTION
**Pull request by kazarmy**
"R2 Theme" is more accurate than "Color Theme", since the palette is from r2 after all.

**Test plan (required)**

Open the Appearance Options dialog (Edit -> Preferences -> Appearance).

R2_Theme

**Closing issues**

### CODE REVIEW

**Comment by kazarmy** [comment]
There's also "Qt Theme" that also sets color, which is somewhat confusing. I suppose one day those 2 theme options will have to merge.

**Comment by ITAYC0HEN** [comment]
Maybe we will change the "Qt Theme" to "Interface Theme" and keep the Color Theme, Unless we'll find a better name for it.

I don't like calling it "r2 theme" since Cutter users shouldn't worry about r2 or not r2. They just want to change the theme. In the near future, we will merge a very nice theme editor that @optizone is working on, stay tuned :)

**Comment by kazarmy** [comment]
> Maybe we will change the "Qt Theme" to "Interface Theme" and keep the Color Theme, Unless we'll find a better name for it.

sgtm

> I don't like calling it "r2 theme" since Cutter users shouldn't worry about r2 or not r2.

ok

**Comment by kazarmy** [comment]
> Unless we'll find a better name for it.

I wanted to suggest "Disasm Theme" but then realized the hexdump could also use some color.

**Comment by ITAYC0HEN** [comment]
Exactly, and it also affects the navigation omni bar, and the overview, and graph nodes, and backgrounds, etc

**Pull request closed without merging**
