### PR TITLE
Refactored Qt project structure

### PR DESCRIPTION
**Pull request by AntonReborn**
### What was the problem & What has been changed: ###
While putting everything in `.pro` file often happens merge conflicts, when at least one file is added to the project. Using `.pri` structure only the changes within a directory will have a conflict. As well, Qt Creator displays such projects much better. It's easier to navigate.

### CODE REVIEW

**Comment by AntonReborn** [comment]
I can see, that the `meson_parse_qmake` should be adjusted to the `.pri` structure.

**Comment by a1ext** [comment]
Why this structure is better?

**Comment by AntonReborn** [comment]
@a1ext less merge conflicts amount,.I'm not sure how is it painful for this project. But usually, the type of structure when all files are declared in one `.pro` leads to spending extra time for each contributor on resolving conflicts each time the new file has been added on a master branch.

**Comment by thestr4ng3r** [comment]
I'm not sure if this makes sense right now since we are about to drop qmake completely anyway. I'll check how much work it would be to adjust both the parser in meson and cmake.
Can you show by screenshots or something what the exact difference in QtCreator is?

**Comment by AntonReborn** [comment]
Previous structure:
old_struct

New structure:
new_struct

**Comment by xarkes** [comment]
I think as of today it represents too much work to adjust the parser in meson and cmake.
As @thestr4ng3r mentioned, we will drop qmake eventually since even Qt is not planning to maintain it.
I am closing the PR, thanks for the proposal though!

**Pull request closed without merging**
