### PR TITLE
Use r2 c api for reading comments.

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

C api allows specifying address directly thus avoiding unnecessary reads caused by seek(rb=true).  There is room for further improvements not refreshing comments during cursor blinking and not having cmdRawAt cause 2*4096 byte reads. With these changes the hexwidget is somewhat usable during debugging compared to.

**Test plan (required)**

Open hexwidget during debuging, try selecting a range of bytes. Compare the performance before and after the patch.

**Closing issues**

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
> Open hexwidget during debuging, try selecting a range of bytes

works well :)


> There is room for further improvements not refreshing comments during cursor blinking and not having cmdRawAt cause 2*4096 byte reads. With these changes the hexwidget is somewhat usable during debugging compared to.

should we have issue for these?

**Comment by ITAYC0HEN** [comment]
For some reason, `rip` flag shown in the hexdump and printed in console is not synced with the value of `rip` register

**Comment by karliss** [comment]
Confirmed register flags are acting weird in Cutter but that's not part of this issue. I remember we noticed something similar without debugging. That isn't really related to this PR. Will create separate issue for that.

**Comment by karliss** [comment]
> should we have issue for these?

Created issue for seek/4k read thing. Hexwidget querying things too often would be solved by the hexwidget highlighting architecture issue.

**Pull request merged**
