### PR TITLE
Reset breakpad to buildable commit

### PR DESCRIPTION
**Pull request by optizone**

### CODE REVIEW

**Comment by karliss** [comment]
Appveyor build didn't stop when breakpad compilation failed, instead it broke much later. How about adding `&& exit /b 1` at least for msbuild so that it detects when build fails? Otherwise looks good for temporary solution.

**Comment by optizone** [comment]
Yeah, sounds good. Also builds with meson does not try to link breakpad to Cutter

**Comment by xarkes** [comment]
Are you adding the `&& exit /b 1` or should I merge?

**Comment by optizone** [comment]
I added. Now let's make sure it works fine (commit test should fail and commit final should pass) and you can merge

**Pull request merged**
