### PR TITLE
Allow local development using Docker

### PR DESCRIPTION
**Pull request by 0x24D**
This pull request contains 3 changes:
1. Update Makefile and add Dockerfile-dev to deploy local files rather than pulling from Master branch.
2. Update Dockerfile-dev to compile radare2 before compiling cutter, previously if any file had changed in cutter then radare2 would be recompiled even though nothing had changed. This fixes this problem.
3. Add .dockerignore to only copy required files when deploying to Docker, for both Dockerfile and Dockerfile-dev, size reduced from >150mb to 44mb.

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
@ps1337 it would be Greta if you'll review these suggested changes

**Comment by ps1337** [comment]
As for the readme, dockerfile and makefile: looks good to me

Regarding the build scripts: I'm not too involved in the cutter build process but isn't there some build script for r2/cutter that can be re-used for this? Just a suggestion though

**Comment by 0x24D** [comment]
@ps1337 There is a *build.sh* script that builds radare2 and cutter in one go which I have copied to *build-cutter.sh* and THEN moved the relevant radare2 section to *build-radare2.sh* so that it can be ran separately. 

To do as suggested I could update the *build.sh* script to run as it is currently when no flags are provided and only run the radare2 or non-radare2 sections when a -r or -c flag is provided respectively. Thus removing the need for the extra scripts.

**Comment by xarkes** [comment]
Just for information, I think we agreed to remove `build.sh` from Cutter code base, as only a single `cmake` command is sufficient to build Cutter.
So I would say it's best to add a specific build script to build it for Docker.

**Comment by ps1337** [comment]
That sounds good to me, +1



-----Original Message-----

**Comment by 0x24D** [comment]
Okay, so the *build.sh* script should be moved to the *docker* subdirectory and then updated as required to remove the need for the extra *build-\** scripts?

**Comment by xarkes** [comment]
You can remove `build.sh` only if the build process is checked and if the build instructions are updated.
I think it won't fit in that PR, so better not touch it for now I would say.

**Pull request merged**
