### PR TITLE
Separate graph layout code from GraphView.

### PR DESCRIPTION
**Pull request by karliss**
Goal of these changes is to simplify development and reusability of graph layout code.

* Easier to work on two smaller and simpler modules 
* Allow experimenting with alternative layout algorithms. Multiple of them can be used if it turns out that there is trade off between performance and readability.

This PR should contain only code refactoring, any changes in behavior are unintentional.

**Test plan (required)**

* Open an executable with some medium to big functions using this version and master
* Visually compare the output, it should be identical

**Closing issues**
None

### CODE REVIEW

**Comment by karliss** [comment]
Planned changes are mostly implemented. While doing the testing I found some changes resulting image, need to investigate if they are caused by my changes, slightly different cutter/r2 version, original code isn't deterministic.

**Comment by ITAYC0HEN** [comment]
This is a great idea, love it! Will find the time to dig into it soon :)

**Comment by ITAYC0HEN** [comment]
> While doing the testing I found some changes resulting image

I don't understand what did you mean?
btw, do you have telegram account? if so, please ping me there @megabeets

**Comment by karliss** [comment]
Regression: edges in graph overview don't have colors.

**Comment by karliss** [comment]
> > While doing the testing I found some changes resulting image
> 
> I don't understand what did you mean?
> btw, do you have telegram account? if so, please ping me there @megabeets

There were some minor differences in layout compared to .appimage version, but it turned out that was caused by differences in r2 version not my changes.

**Comment by karliss** [comment]
Rebased to resolve merge conflict.

**Pull request merged**
